[en]
  languageName = "English"
  languageCode = "en"
  weight = 2
  title = "Zaheen Ahmed Deep"
  [en.params]
    tagline = "Infrastructure Engineer"

[bn]
  languageName = "বাংলা"
  languageCode = "bn"
  weight = 1
  title = "জাহীন আহমেদ দীপ"
  [bn.params]
    tagline = "অবকাঠামো প্রকৌশলী"
