# boolean type, the global switch for TOC in posts.
toc = true
# the avatar on sidebar, should be a relative path to /assets.
avatar = "img/commons/avatar.jpg"
author = "zdeep"

[assets]
  # Self-hosted static assets, default to false. If true, the assets will be hosted on your own server.
  self_host = false

[social]
  name = "Zaheen Ahmed Deep"
  url = "https://linkedin.com/in/zaheenadeep"

[[social.links]]
  type = "github"
  id = "zaheenadeep"
  icon = "fab fa-github"

[[social.links]]
  url = "https://linkedin.com/in/zaheenadeep"
  icon = "fab fa-linkedin"

[[social.links]]
  type = "email"
  id = "your.email@example.com"
  icon = "fas fa-envelope"

[[social.links]]
  type = "rss"
  icon = "fas fa-rss"
  noblank = true  # will not open in new window

[comments]
# Global switch for the post-comment system. [true | false]
enable = true
# The provider options are as follows: [disqus | utterances | giscus]
provider = ""

# Disqus options
[comments.disqus]
# fill with the Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
shortname = ""

# utterances settings › https://utteranc.es/
[comments.utterances]
# <gh-username>/<repo>
repo = ""
# < url | pathname | title | ...>
issue_term = ""

# Giscus options › https://giscus.app
[comments.giscus]
# <gh-username>/<repo>
repo = "zaheenadeep/chirpy-giscus"
repo_id = "R_kgDOQSLhsA"
category = "Comments"
category_id = "DIC_kwDOQSLhsM4CxndW"
# optional, default to 'pathname'
mapping = "pathname"
# optional, default to '0'
strict = "0"
# optional, default to 'bottom'
input_position = "top"
# optional, default to site language
lang = "en"
# optional, default to the value of `1`
reactions_enabled = "1"
